# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.box = "debian/buster64"
  config.vm.hostname = "debian"

  config.vm.network "private_network", ip: "192.168.1.33"
  config.vm.provision "ansible", playbook: "playbook.yml"

end