apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi-deployment
  labels:
    app: userapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
        - name: userapi
          image: salamander93/ece-devops-2021:latest
          ports:
            - containerPort: 5000
          env: 
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mysql-url
---
apiVersion: v1
kind: Service
metadata:
  name: userapi-service
spec:
  type: NodePort
  selector:
    app: userapi
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
